### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Fidode07** [CorsairOfficial/cue-sdk-python#17] opened 2022-08-10 12:56 UTC
```
Traceback (most recent call last):
  File "C:/Users/Fido_de07/Desktop/DEVELOPMENT/DEVELOPMENT/RGBSynchroner/Windows/tests.py", line 1, in <module>
    from cuesdk import CueSdk
  File "C:\Users\Fido_de07\AppData\Local\Programs\Python\Python38\lib\site-packages\cuesdk\__init__.py", line 2, in <module>
    from .structs import *
  File "C:\Users\Fido_de07\AppData\Local\Programs\Python\Python38\lib\site-packages\cuesdk\structs.py", line 49, in <module>
    class CorsairChannelInfo():
  File "C:\Users\Fido_de07\AppData\Local\Programs\Python\Python38\lib\site-packages\cuesdk\structs.py", line 51, in CorsairChannelInfo
    devices: list[CorsairChannelDeviceInfo]
TypeError: 'type' object is not subscriptable
```

 I imported "from cuesdk import CueSdk". Do things like "import cuesdk" throws the same Exception.

Python Version: 3.8
Keyboard: K55 RGB
iCUE Installed: Yes
sdk.connect() doesn't return False. get_devices() List is empty and get_device_count() is 0. 
C++ is installed but another Version (I tryed yours too).

**Comment by intrueder** [comment] 2022-08-10 16:18
@Fidode07 uh, oh, K55 again🤕

I guess the issue is similar to [cue-sdk-python#15](https://github.com/CorsairOfficial/cue-sdk-python/issues/15#issuecomment-1204940577)  and [cue-sdk-node#21](https://github.com/CorsairOfficial/cue-sdk-node/issues/21)
I'd suggest using [version 4.23](https://downloads.corsair.com/Files/CUE/iCUESetup_4.23.137_release.msi) until the issue is fixed in iCUE.

Could you please check if v4.23 works for you?

**Comment by Fidode07** [comment] 2022-08-10 19:26
I've tried it currently, but unfortunately the same error again. I used this SDK a few months ago (February I think). At that time everything still worked.

**Comment by Fidode07** [comment] 2022-08-10 19:43
Okay. I've downgraded to the v3.38.88. And the cuesdk was raising the same error so i downgraded the cuesdk to 1.2.0. And now it's working.

**Comment by intrueder** [comment] 2022-08-11 20:28
@Fidode07 My bad, type annotations using builtin collection require Python 3.9 (see [PEP 585](https://peps.python.org/pep-0585/))
Next release will address the issue. Thanks for your help.

**Closed** 2022-08-13 11:39 UTC
Labels: bug
