### ISSUE TITLE
events.py example file glitch.

### ISSUE THREAD

**Issue by TheTheoM** [CorsairOfficial/cue-sdk-python#15] opened 2022-05-29 16:29 UTC
events.py example file does not recognise K95 keyboard events after ICUE update. It recognises unplug/replug but no g key inputs.

**Comment by intrueder** [comment] 2022-06-02 10:36
@TheTheoM may I know how many keyboards are connected to your PC? Can you share a list of devices displayed on the iCUE home tab?

**Comment by TheTheoM** [comment] 2022-06-02 15:14
H100 plat. comman pro, LNC, LNP, k95P, glaive, vengeance.
1 keyb.

**Comment by TheTheoM** [comment] 2022-06-02 15:16
When i run the py, it shows in icue as connected.

**Comment by intrueder** [comment] 2022-06-03 08:31
Well, it's weird.. have you tried restarting iCUE (click "Quit" in the system tray icon menu, and start again)? Because there is nothing we can do on the SDK side. Example of output with the latest iCUE and SDK versions:

```
Working... Press any G/M key or connect/disconnect Corsair device to see events in action
Press 'q' to close program...
Event: CorsairEventId.KeyEvent
 Device id: 69c529e9ec734c3651beb9301850bbc8
    Key id: CorsairKeyId.Kb_G1
 Key state: pressed
Event: CorsairEventId.KeyEvent
 Device id: 69c529e9ec734c3651beb9301850bbc8
    Key id: CorsairKeyId.Kb_G1
 Key state: released
```

**Comment by intrueder** [comment] 2022-08-04 08:33
Hi @TheTheoM, 
I can confirm now, that there is an issue in iCUE. It depends on a set of devices connected to a PC.
The issue has been introduced in iCUE v4.24, and is not yet fixed. I think the best option, for now, is to downgrade iCUE to v4.23 and use it until the issue is fixed.

**Comment by intrueder** [comment] 2022-09-26 12:08
Hi @TheTheoM , I'm closing this as iCUE v4.28 has fixed the issue

**Closed by intrueder** 2022-09-26 12:08 UTC
